### ISSUE TITLE
Translations not deleted automatically once related "translatable" entity is deleted

### ISSUE THREAD

**Issue by lex0r** [wintercms/wn-translate-plugin#12]
### Winter CMS Build

dev-develop

### PHP Version

8.0

### Database engine

MySQL/MariaDB

### Issue description

When a translatable model gets deleted (physically from the database) no related translations of that model get deleted automatically from winter_translate_attributes and winter_translate_indexes.

### Steps to replicate

1. Create a translatable model
2. Save it to the database
3. Delete it

Expected result:
All related translations should be removed

Actual result:
Translations remain in winter_translate_attributes and winter_translate_indexes

**Comment by Teranode** [comment]
Relevant pull https://github.com/wintercms/wn-translate-plugin/pull/20
