### ISSUE TITLE
Need installation/migration instructions

### ISSUE THREAD

**Issue by multiwebinc** [wintercms/wn-translate-plugin#13]
I was previously using rainlab/translate (I believe v1.8.7), but I wanted to give this plugin a try, however I couldn't find instructions for installing this plugin or migrating from rainlab/translate.

This is what I did, which appears to have worked to at least get the page to render, however, I am unsure if the messages were migrated. I would assume not:

```
php artisan plugin:remove rainlab.translate
composer require winter/wn-translate-plugin
php artisan winter:up
```

Unfortunately, there are other plugins I am using that depend on rainlab/translate, so I wouldn't be able to use this one anyway unless the plugin's `$require` property can somehow have multiple choices, like `$require = ['RainLab.Translate|Winter.Translate'];`, can it?

**Comment by LukeTowers** [comment]
`plugin:remove` drops all data related to the original plugin in the database too, so none of your messages would have migrated because you removed the data. The correct way is to use composer and then just replace the rainlab dependency with the Winter dependency. Plugin dependencies should just work with the aliasing functionality built into Winter so long as you're using the latest version of Winter.

Side note for @bennothommo, I think we should add a warning message to the `plugin:remove` command requiring confirmation of typing the plugin name again and provide a flag to delete the files only (i.e. don't run the down methods on the migrations)

**Comment by multiwebinc** [comment]
Thanks for the quick replies, guys. If I simply do `composer require winter/wn-translate-plugin`, it keeps using RainLab. If I then delete the `plugins/rainlab/translate` directory, I get an error saying something along the lines of the `_` filter not existing. I then re-executed the above composer command and then did `php artisan winter:up`, and I get errors in the migration:

```
Winter.Translate

In Connection.php line 669:
                                                                                                                                                                                                                                         
  SQLSTATE[HY000]: General error: 1 table "rainlab_translate_messages" already exists (SQL: create table "rainlab_translate_messages" ("id" integer not null primary key autoincrement, "code" varchar null, "message_data" text null))  
                                                                                                                                                                                                                                         

In Exception.php line 18:
                                                                                       
  SQLSTATE[HY000]: General error: 1 table "rainlab_translate_messages" already exists  
                                                                                       

In PDOConnection.php line 82:
                                                                                       
  SQLSTATE[HY000]: General error: 1 table "rainlab_translate_messages" already exists
```

Then going to the page, I get:

```
SQLSTATE[HY000]: General error: 1 no such table: winter_translate_locales (SQL: select "name", "code" from "winter_translate_locales" where "is_enabled" is not null and "is_enabled" = 1 order by "sort_order" asc)
```

I had to update several of the migration files to do checks to create the tables only if they don't exist already. I'll make a PR to address this.

**Comment by damsfx** [comment]
For sites using plugins that reinstall Rainlab plugins (e.g. Offline.Mall through its dependencies), I have modified my composer.json file to get rid of them systematically: 
```json
"pre-autoload-dump": [
    "rm -rf plugins/rainlab"
],
```
Maybe not the best idea, but it works.

**Comment by bennothommo** [comment]
@multiwebinc in the normal scheme of things, that shouldn't happen. RainLab should get disabled by the Winter version of the plugin automatically, and the Winter version is used instead.

What version of RainLab's translate plugin was installed before you tried installing Winter's translate plugin? I might need to test this myself and see what's happening.

**Comment by bennothommo** [comment]
@damsfx The plugin replacement feature in Winter is supposed to stop automatic installs of the plugins happening too - essentially, the Winter version of the plugin is supposed to resolve the dependency of the Rainlab plugin. What way are you installing Mall that ends up installing the Rainlab plugin?

**Comment by bennothommo** [comment]
@LukeTowers true, but even if they're included and installed, they shouldn't be used due to plugin replacement.

**Comment by LukeTowers** [comment]
@bennothommo I made a comment about it in the other PR but I think the original issue is because the rainlab version went up but the version we're replacing didn't so the replacement system didn't kick in properly.

**Comment by bennothommo** [comment]
Ah gotcha.

**Comment by multiwebinc** [comment]
> What version of RainLab's translate plugin was installed before you tried installing Winter's translate plugin?

Pretty sure it was v1.8.7.

**Comment by LukeTowers** [comment]
@multiwebinc are you able to replicate the issue in a fresh install of Winter and then post the replication instructions here?

**Comment by damsfx** [comment]
> @damsfx The plugin replacement feature in Winter is supposed to stop automatic installs of the plugins happening too - essentially, the Winter version of the plugin is supposed to resolve the dependency of the Rainlab plugin. What way are you installing Mall that ends up installing the Rainlab plugin?

With composer.
Offline.Mall plugin required his dependencies in his [composer.json file](https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/d652bf943481af15f637d9fc4a4ac05e96abf3b2/composer.json#L26-L28).

So when the command `php artisan winter:version` is executed, errors appear because the Rainlab plugins are present.
