### ISSUE TITLE
Scanner does not match plurals, and other filters

### ISSUE THREAD

**Issue by multiwebinc** [wintercms/wn-translate-plugin#15]
Checking the source, the `processStandardTags()` method seems to do a few regex matches to find translatable strings, however, it doesn't match for these filters:

`__` (double underscore)
`transRaw`
`transRawPlural`
`localeUrl`

I haven't tested it extensively, however this regex appears to work for me (I have about 400 strings):

```regex
{{\s*(["'])((?:(?:(?!\1)).)+)\1\s*[|]\s*(?:_{1,2}|transRaw(?:Plural)?|localeUrl)\s*(?:\([^\)]+\)\s*)?}}
```

Here's the PHP:

```php
    protected function processStandardTags($content)
    {
        preg_match_all('#{{\s*(["\'])((?:(?:(?!\1)).)+)\1\s*[|]\s*(?:_{1,2}|transRaw(?:Plural)?|localeUrl)\s*(?:\([^\)]+\)\s*)?}}#', $content, $match);
        return $match[2] ?? [];
    }
```

**Comment by multiwebinc** [comment]
On a side note, that should probably be `$matches`, not `$match`, since it's an array.

Also, this is great and all, but I was wondering if there was a way to actually use Twig's built-in functions to do this instead?

**Comment by LukeTowers** [comment]
Do those functions all support message translations? Also what do you mean by "using Twig's built-in functions to do this instead"?

**Comment by multiwebinc** [comment]
@LukeTowers 

> Do those functions all support message translations?

I'm not sure I understand your question. The regex above should handle the 4 regexes currently used, plus also the other filters listed in my post.

> Also what do you mean by "using Twig's built-in functions to do this instead"?

Well I mean, Twig already parses the files for many things, including the translation filters. So I'm wondering if there would be some sort of functionality in the Twig library that could be used to find all occurrences of a particular filter being used.
