### ISSUE TITLE
Message exporting and importing creates empty messages

### ISSUE THREAD

**Issue by multiwebinc** [wintercms/wn-translate-plugin#16]
Steps to reproduce:

1. Make sure you have at least one language in "Manage languages" and set it as default. I added `en` and `es`.
2. If there are no messages, under "Translate messages", scan for messages to add new messages.
3. Export messages to CSV file and save the file. This file should have the columns, `code`, `default`, `en`, and `es`.
4. Import CSV file and select "Auto match columns"

The imported messages will have a `message_data` JSON object that contains empty strings.

Example actual value:

```json
{"x":"Welcome to my blog.","en":"","es":""}
```

Expected value:

```json
{"x":"Welcome to my blog."}
```

This is a problem because if the cache is ever cleared (Translate messages > Clear cache), empty strings will be outputted to the page instead of the default value because of this code: 

https://github.com/wintercms/wn-translate-plugin/blob/7fa0de32e10f2674e3b7f4f2fa4322ef33bd6fc5/models/Message.php#L69-L71

**Comment by bennothommo** [comment]
@multiwebinc I've given this a test - I did not originally see the same issue when none of the translations had been entered for either `en` or `es`. It still showed the default translation (`x`).

It was only after I entered in the `en` translations but left the `es` translations blank that I got the issue. I'll try your fix now and will merge if it works.

**Comment by bennothommo** [comment]
I've just had a further thought on this - I believe that there may be scenarios where it would be legitimate for a particular language string might be empty for a certain language - for example, if there's no literal translation or if a feature isn't used for a certain language. I think we can't be presumptuous in this scenario that it needs to therefore use the default language.

@multiwebinc @LukeTowers do you have any thoughts on this?

**Comment by LukeTowers** [comment]
Since this is just for the import process the fundamental question that needs to be answered is "is there a change in behavior when exporting and then importing with the current logic?" It sounds like there might be because it turns non existent values into empty strings which prevents fallbacks from being used.

@bennothommo are you suggesting that people could be purposely setting those translated values to empty strings? If so, two things to consider, first, does the current code actually allow for that state to be reached intentionally, and second is that actually a valid use case?

If empty strings is a valid and separate use case from not set strings then another solution could be to distinguish between an empty string value and a null value in the exporting of the data.

**Comment by multiwebinc** [comment]
> If so, two things to consider, first, does the current code actually allow for that state to be reached intentionally, and second is that actually a valid use case?

Those are both very good points. It doesn't seem possible to reach this state intentionally since setting the translation value to an empty string in the backend removes that language from the JSON value in the database. To intentionally reach this state, the user would need to either manually edit the entry in the database or import a CSV and then clear the cache. In either case, they would need to already be familiar with how this plugin behaves with empty strings unless they arrived there by accident.

As for it being a valid use case, I would lean more on the side of "no", since when getting something translated, you would typically pass all of the strings to the translator. The translator will not necessarily know that a particular string needs to be left blank only for a particular language and the CSV output does not include a column for notes. There are other ways to accomplish hiding/showing a string for a specific language and I would feel that translating something with an empty string would be more of a hack than a feature.

**Comment by LukeTowers** [comment]
Fixed by https://github.com/wintercms/wn-translate-plugin/commit/eb1a6ca8bade819c1548e5d43e22c67e9183c653
