### ISSUE TITLE
Error code: 404 if you try to directly access page in different language

### ISSUE THREAD

**Issue by dynamiccontent** [wintercms/wn-translate-plugin#3]
I don't understand how everyone missed this when they designed this plugin. This is important for multilingual pages. If my client has opened the page in language 1 and I send him the link to page on language 2 url he will receive error 404.

Will this be fixed in the future or what is your advice how to deal with this?

Example below:

This is so it will display menu in the top right corner:
![demo1](https://user-images.githubusercontent.com/56940608/111764222-472b5100-88a3-11eb-850f-b1e92a36dabf.png)
![demo2](https://user-images.githubusercontent.com/56940608/111764269-55796d00-88a3-11eb-97bc-78d496266e65.png)
![demo3](https://user-images.githubusercontent.com/56940608/111764295-590cf400-88a3-11eb-805c-12c251abbd60.png)

Everything will work fine if I switch languages via language picker from english to slovenian it will switch the url from https://example.com/blogslovenian to https://example.com/blogenglish without problems.

I have added different url for each language on page:
![demo4](https://user-images.githubusercontent.com/56940608/111764776-dfc1d100-88a3-11eb-8e62-8247a53f269e.png)
![demo5](https://user-images.githubusercontent.com/56940608/111764782-e2242b00-88a3-11eb-8f8f-6c53251b3804.png)

This will work when I am switching languages via language picker:
![demo6](https://user-images.githubusercontent.com/56940608/111765270-77bfba80-88a4-11eb-8781-8a7602bec631.png)
![demo7](https://user-images.githubusercontent.com/56940608/111765280-7abaab00-88a4-11eb-86cd-6c76bd34daa7.png)

The problem is when I try to access different language url manually. For example the page is set to Slovenian (https://example.com/blogslovenian) via language picker and I access english url (https://example.com/blogenglish) manually it will 404.
![demo8](https://user-images.githubusercontent.com/56940608/111765430-9de55a80-88a4-11eb-954f-2d3f82ac155f.png)

Here is the error log:
![demo9](https://user-images.githubusercontent.com/56940608/111765668-f0267b80-88a4-11eb-85b2-2e6fa3b4ac65.png)

![demo10](https://user-images.githubusercontent.com/56940608/111765680-f3ba0280-88a4-11eb-8161-42c00be3fb55.png)

**Comment by mjauvin** [comment]
Did you set "forceUrl = 1" in the localePicker component ?

**Comment by dynamiccontent** [comment]
> 
> 
> Did you set "forceUrl = 1" in the localePicker component ?

It's the same either way. I have tested this so many different ways always the same error. I can't put a site like this into production...

**Comment by mjauvin** [comment]
I have many sites in production without this issue. Something is not properly configured.

Can you send me a link to the website so I can take a look? You can connect on our discord channel and PM me directly.

**Comment by dynamiccontent** [comment]
The sites are not public as they are still work in progress. I have to reconfigure the server so you will be able to have a look. Give me 30 minutes and I will PM you on discord.

**Comment by mjauvin** [comment]
Can you show me the full CMS page definition for a page having the problem? Did you properly set the slug in both languages?

**Comment by dynamiccontent** [comment]
Confirmed by mjauvin that why I am trying to do is not supported. You need to reference the language suffix in the url so the site knows what language to load.
