### ISSUE TITLE
Incorrect URL encoding with onSwitchLocale

### ISSUE THREAD

**Issue by arvislacis** [wintercms/wn-translate-plugin#36]
I mentioned this issue on Discord but as I didn't get any feedback, I will try to rewrite and formulate it here.

I have a page with dynamic device filter which updates page URL when user makes changes in the front-end so the resulting URL is something like `?filter=1&M[]=LENOVO&M[]=SAMSUNG` but then when user interacts with language switcher component and `onSwitchLocale` AJAX event is triggered then the user is redirected to page containing filter `?filter=1&M%5B0%5D%5B%5D=LENOVO&M%5B1%5D%5B%5D=SAMSUNG`. If we decode that then we can see that it becomes `?filter=1&M[0][]=LENOVO&M[1][]=SAMSUNG` which is differnet data structure than the initial filter before language switch.

- Initial URL: `?filter=1&M[]=LENOVO&M[]=SAMSUNG`

- After language switch: `?filter=1&M%5B0%5D%5B%5D=LENOVO&M%5B1%5D%5B%5D=SAMSUNG` or `?filter=1&M[0][]=LENOVO&M[1][]=SAMSUNG`

- Expected output after language switch: `?filter=1&M[]=LENOVO&M[]=SAMSUNG` or `?filter=1&M[0]=LENOVO&M[1]=SAMSUNG` (can be encoded, doesn't matter but the underlying data structure should be preserved the same).

**Comment by mjauvin** [comment]
Did you check in the code exactly what's causing this?

**Comment by arvislacis** [comment]
@mjauvin Not yet, I will try to dig into that a bit later... Currently I know that when user switches languages with default language switcher then `onSwitchLocale` AJAX event is triggered which then redirects user to the page with incorrect filter.

**Comment by mjauvin** [comment]
There's probably a bug in the LocalePicker component's `withPreservedQueryString()` method

ref. https://github.com/wintercms/wn-translate-plugin/blob/main/components/LocalePicker.php#L192-L222

**Comment by mjauvin** [comment]
Until tthe bug is found/fixed, you could handle the following event and fix the query yourself:
```
         Event::listen('translate.localePicker.translateQuery', function($page, $params, $oldLocale, $newLocale) {
         });
```

**Comment by mjauvin** [comment]
Although the bug is probably caused by the next call, which wouldn't really help:
```
        $query = http_build_query($translatedQuery ?: $query);
```

**Comment by arvislacis** [comment]
> Although the bug is probably caused by the next call, which wouldn't really help:
> 
> ```
>         $query = http_build_query($translatedQuery ?: $query);
> ```

Yes, looks like this is the problematic part, did some debugging. Before this call the value of `$query` is:

```
array (
  'filter' => '1',
  'M' =>
  array (
    0 => 'NOKIA',
    1 => 'SAMSUNG',
  )
)
```

**Comment by arvislacis** [comment]
@mjauvin The problematic line is:

https://github.com/wintercms/wn-translate-plugin/blob/d8e7f6c421b8eb22f768e797acbd1439b9b4e6c9/components/LocalePicker.php#L88

To be more specific - `Redirect::to()` returns incorrect:

```
HTTP/1.0 302 Found
Cache-Control: no-cache, private
Date:          Wed, 15 Jun 2022 12:41:14 GMT
Location:      [XXX]?filter=1&M%5B0%5D%5B%5D=LENOVO&M%5B1%5D%5B%5D=SAMSUNG
```

**Comment by arvislacis** [comment]
`$this->translator->getPathInLocale($pageUrl, $locale)` returns `?filter=1&M%5B0%5D=LENOVO&M%5B1%5D=SAMSUNG` which is correct so far and then `Redirect::to()` turns that into `?filter=1&M%5B0%5D%5B%5D=LENOVO&M%5B1%5D%5B%5D=SAMSUNG`

**Comment by mjauvin** [comment]
Oh, nice catch. I'll look into it.

**Comment by mjauvin** [comment]
@arvislacis If you want to apply a monkey patch in the meantime, please apply this patch locally to `vendor/winter/storm`:
```diff
diff --git a/src/Router/UrlGenerator.php b/src/Router/UrlGenerator.php
index b86ac47a..59992943 100644
--- a/src/Router/UrlGenerator.php
+++ b/src/Router/UrlGenerator.php
@@ -15,8 +15,8 @@ class UrlGenerator extends UrlGeneratorBase
      */
     public function to($path, $extra = [], $secure = null)
     {
-        $url = parent::to($path, $extra, $secure);
-        return static::buildUrl($url);
+        return $url = parent::to($path, $extra, $secure);
+        #return static::buildUrl($url);
     }  
 
     /**    
    
```

**Comment by arvislacis** [comment]
@mjauvin So far patch works fine but I will test it more. After language switch user is redirected from `?filter=1&M[]=NOKIA&M[]=SAMSUNG` to `?filter=1&M%5B0%5D=NOKIA&M%5B1%5D=SAMSUNG` so the new URL contains encoded characters but, yes, the primary issue of array indexes looks to be solved.

Also `return $url = parent::to($path, $extra, $secure);` could be reduced to `return parent::to($path, $extra, $secure);` - but that's just a super minor thing.

**Comment by arvislacis** [comment]
@mjauvin Ok, thanks a lot for information and your help.

**Comment by arvislacis** [comment]
Not solved, as I commented in https://github.com/wintercms/storm/pull/90#issuecomment-1166517189 and added additional test case.
