### ISSUE TITLE
How to set language from frontend?

### ISSUE THREAD

**Issue by gviabcua** [wintercms/wn-translate-plugin#43]
How to set language from frontend?
This don`t work

```
$translator = Translator::instance();
$translator->setLocale($locale, true);
```

**Comment by mjauvin** [comment]
Why not use the localeSwitcher component?

**Comment by gviabcua** [comment]
> Why not use the localeSwitcher component?

No, I am using personal language for each user. And need to change language after user login.

**Comment by mjauvin** [comment]
Then you need to redirect to the right location

**Comment by mjauvin** [comment]
look at how the localeSwitcher does it.

**Comment by gviabcua** [comment]
> look at how the LocalePicker component does it. ref. https://github.com/wintercms/wn-translate-plugin/blob/main/components/LocalePicker.php#L75-L92
> 
> ```
>   public function onSwitchLocale()
>   {
>       if (!$locale = post('locale')) {
>           return;
>       }
> 
>       // Remember the current locale before switching to the requested one
>       $this->oldLocale = $this->translator->getLocale();
> 
>       $this->translator->setLocale($locale);
> 
>       $pageUrl = $this->withPreservedQueryString($this->makeLocaleUrlFromPage($locale), $locale);
>       if ($this->property('forceUrl')) {
>           return Redirect::to($this->translator->getPathInLocale($pageUrl, $locale));
>       }
> 
>       return Redirect::to($pageUrl);
>   }
> ```

This work so good! Thanks
