### ISSUE TITLE
Translate not work with RelationManager Popup

### ISSUE THREAD

**Issue by over12** [wintercms/wn-translate-plugin#55]
I'm using the plugin and I realized that when I use a relationmanager popup it doesn't work..
for example, if you notice my print, my model is configured all right, but the page popup doesn't show.

![Screenshot_13](https://user-images.githubusercontent.com/12565400/218445909-3f5a81ea-0816-4fd6-8807-ae5c9814a5a7.png)

Any solution for this problem?

Thanks!

**Comment by LukeTowers** [comment]
@over12 what was your solution?
