### ISSUE TITLE
Wrong version when installing with composer

### ISSUE THREAD

**Issue by xitara** [wintercms/wn-translate-plugin#58]
When installing this plugin with `composer require winter/wn-translate-plugin`, a version for octoberCMS v3.1 will be installed in `plugins\winter\wn-translate`

Tested with a clean install from the dev-channel of winterCMS

**Comment by bennothommo** [comment]
Thanks for letting us know @xitara - we'll have that fixed shortly.

**Comment by LukeTowers** [comment]
Should be fixed now
