### ISSUE TITLE
URL with locale code

### ISSUE THREAD

**Issue by m-paniez9292** [wintercms/wn-translate-plugin#77]
### Winter CMS Build

1.2

### PHP Version

8.0

### Database engine

MySQL/MariaDB

### Plugins installed

Winter.Translate, winter.Page

### Issue description

Hi,
I would like to use 2 languages for my website and all seems good.

I have the localepicker to change the current language, but it's by javascript and menu URLs haven't language code (I use winter.Pages to manage my content).
So, how can I add language/locale code to my menu URLs (ie. www.domain.com/mypage > www.domain.com/en/mypage) and convert my localepicker to html links instead of javascript ?

Thanks

### Steps to replicate

Fresh install + winter.translate + winter.Pages

**Comment by mjauvin** [comment]
Static Menu items titles are translatable

**Comment by mjauvin** [comment]
How do you create your menus?

**Comment by m-paniez9292** [comment]
Hi,
Thanks for your reply.
I create a webpage by Pages > Pages and, after that, I create the menu by Pages > Menus (I refer to my webpage).
And yes, my menus and URL are translated : all about that works well.
But, I would like to add the language code in the URL between domain name and page name like www.domain.com/mypage to www.domain.com/**en**/mypage 
If I do that actually (I put www.domain.com/**en**/mypage in the URL), I have no content and my menus links have the form www.domain.com/**en**?slug=mypage
Thanks

**Comment by mjauvin** [comment]
The language code should be added automatically if using the "page" (see https://wintercms.com/docs/v1.2/markup/filters/page) or "staticpage" (https://github.com/wintercms/wn-pages-plugin/blob/main/docs/documentation.md#linking-to-static-pages) twig filters

**Comment by mjauvin** [comment]
I'll close this since there was no feedback. Feel free to reopen if there's an actual issue.
