### ISSUE TITLE
After Winter CMS update to 1.2.5 can't translate CMS pages title

### ISSUE THREAD

**Issue by oim37** [wintercms/wn-translate-plugin#79]
Hello,

I update wintercms to 1.2.5 and begin receive notice from search engine that title on cms pages same.

The ability to translate titles and meta tags has disappeared - in cms pages, i can only change URL for other languages.
It other plugins blog and static pages its ok. 

![image](https://github.com/wintercms/wn-translate-plugin/assets/6842168/44bce122-a345-41da-8153-d1a2d20594db)

**Comment by mjauvin** [comment]
Is it the same with latest version (1.2.6) ?

**Comment by oim37** [comment]
run composer update and after plugin updated it fixed.. now work good!

Migrating Translate (Winter.Translate) plugin...

   INFO  Running migrations.  

  2.1.5:    Add support for translatable nested forms ................................................ 9ms DONE
  2.1.6:    Improve ML button styling ................................................................ 2ms DONE

Thank you :)

**Comment by mjauvin** [comment]
> On a sidenote, I had dev-main in composer but I had to change it to get the new ML button style
> 
> ```
> "winter/wn-translate-plugin": "~2.1.6",
> ```

How can that be ? dev-main currently is the same thing as 1.2.6.

**Comment by AIC-BV** [comment]
> 1.2.6
You mean 2.1.6 right?

**Comment by mjauvin** [comment]
Right, brain cramp... ;)
